"""All simple 9-regular graphs on n vertices (as complements of (n-10)-regular
graphs generated by geng), tested for modulo-5 orientations."""
import sys, subprocess, itertools
import networkx as nx
from mod5 import has_mod_orientation

n = int(sys.argv[1])
c = n - 1 - 9
proc = subprocess.Popen(["geng", "-q", f"-d{c}", f"-D{c}", str(n)], stdout=subprocess.PIPE, text=True)
tot = good = 0
for line in proc.stdout:
    H = nx.from_graph6_bytes(line.strip().encode())
    G = nx.complement(H)
    E = list(G.edges())
    tot += 1
    if has_mod_orientation(n, E, 5):
        good += 1
    else:
        print("NO MOD-5 ORIENTATION:", line.strip(), flush=True)
    if tot % 5000 == 0:
        print(f"... {tot} tested", flush=True)
print(f"n={n}: {tot} simple 9-regular graphs, {good} have a modulo-5 orientation")
